# Generated by Django 4.1.2 on 2024-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
