# Generated by Django 4.1.2 on 2024-01-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0005_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_log.games')),
                ('participants', models.ManyToManyField(related_name='events_participated', to='user_log.user')),
            ],
        ),
        migrations.CreateModel(
            name='MainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_events', models.ManyToManyField(related_name='sub_events', to='user_log.subevents')),
            ],
        ),
    ]
