# Generated by Django 4.1.2 on 2024-01-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0006_subevents_mainevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevents',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subevents',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='events_participated', to='user_log.user'),
        ),
        migrations.AlterField(
            model_name='subevents',
            name='rules',
            field=models.TextField(null=True),
        ),
    ]
