# Generated by Django 4.1.2 on 2024-01-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0007_alter_subevents_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participation',
            field=models.BooleanField(default=False),
        ),
    ]
