# Generated by Django 4.1.2 on 2024-01-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0008_user_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevents',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participated', to='user_log.user'),
        ),
    ]
