# Generated by Django 4.1.2 on 2024-01-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0009_alter_subevents_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainevent',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
