# Generated by Django 4.1.2 on 2024-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0010_mainevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participated_event',
            field=models.IntegerField(null=True),
        ),
    ]
